### ISSUE TITLE
Sequelize module is out of date

### ISSUE THREAD

**Issue by nueko** [holidayextras/jsonapi-store-relationaldb#18]
Just to make sure that you have read the warning:

```bash
npm WARN deprecated sequelize@3.14.2: security/injection issue with limit/offset fixed in 3.17.0
```

**Comment by theninj4** [comment]
:+1: thanks @nueko

**Comment by theninj4** [comment]
I'd love to fix this, but updating to the latest sequelize gives us loooads of these:
```
Warning: a promise was created in a  handler but was not returned from it
    at process._tickCallback (node.js:419:13)
```
All of our promise usage looks like this:
```
sequelise.doSomethingThatCreatesAPromise().asCallback(......);
```
so I don't think we're meant to be seeing any of these errors, or if we are there's nothing I can do about them.

All input params (including limit and offset) get validated via Joi to be pure numbers, so we've got another layer of validation on top of Sequelize. I'm not too worried about their bugfix and I don't have the time to mess with these anonymous warnings. Probably won't fix?

**Comment by nueko** [comment]
Got it.
As long as i knw, SQL injection will prevented by carefully parse or
sanitize the input param. So if Joi does the job i think it will be ok.

**Comment by pmcnr-hx** [comment]
We are now using the latest release of Sequelize in `v1.1.0` without any of the issues that were preventing updating so closing this.
