### ISSUE TITLE
Sorry, for asking my question here!

### ISSUE THREAD

**Issue by soap** [holidayextras/jsonapi-store-relationaldb#51]
I want to use singular table name where can I customize this parameter?
I know that Sequelize has a parameter tableName but I don't know how to do.

Do you have forum or something for asking technical question?

Sorry and thanks.

**Comment by oliversalzburg** [comment]
You might need https://github.com/holidayextras/jsonapi-store-relationaldb/pull/55 with that, singular names should work.

**Comment by pmcnr-hx** [comment]
#55 has been merged and this issue is fixed in the latest 2.0.0 release.
