### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by oliversalzburg** [holidayextras/jsonapi-store-relationaldb#54]
I noticed quite a few issues that should be easy to fix. Before I start creating dozens of branches and PR, I'd like to know if there is even a point in doing so.

**Comment by paparomeo** [comment]
Hi @oliversalzburg. The answer is yes. You should see progress on PRs being merged. Please submit your PRs if you have. The trivial and obvious fixes should be merged quite quickly. I'll be devoting time to clear the backlog this week. Thank you for your contribution.

**Comment by oliversalzburg** [comment]
Awesome. Thanks :)
