### ISSUE TITLE
Allow relation and table names to be user-defined

### ISSUE THREAD

**Issue by oliversalzburg** [holidayextras/jsonapi-store-relationaldb#57]
I'm trying to integrate jsonapi-server into our stack and attaching our existing data is the issue I am currently focusing on. I'm already somewhat confident that this module will not work for us, but I'm ready to give it a shot. 

The biggest issue is sequelize trying to force certain names for relations and tables. How to work around this issue is explained in the [legacy tables documentation](http://docs.sequelizejs.com/manual/advanced/legacy.html). This module currently does not provide the means to access these configuration options. I would like to change that.

Is that in-line with the design of this module? Is this already possible and I'm just missing the right options?

**Comment by oliversalzburg** [comment]
I'm actually a bit confused as to how relationships are modeled. I have a resource like this:
```js
jsonApi.define( {
	namespace : "json:api",
	resource : "user",
	description : "A user.",
	handlers : usersHandler,
	searchParams : { },
	attributes : {
		email : jsonApi.Joi.string().email()
			.description( "The users primary email address" )
			.example( "john.smith@example.com" ),
		createdBy : jsonApi.Joi.one( "user" )
	}
} );
```

Now, when I try to work with this resource, jsonapi-server will try to create a relation named `user-createdBy`. When I was digging into the code, it seemed like this module tries to create an entire new table to store this relationship, even though it's 1-n and the FK is stored with the user resource itself.

So, why is this done?

**Comment by paparomeo** [comment]
The generic data store packages, like `jsonapi-store-relationaldb` and `jsonapi-store-mongodb`, were designed to have an opaque backing store that isn't really meant to be created or accessed directly, and is created from scratch and managed by the store module.

Also at the core of the design of `jsonapi-server` is that each resource can have a completely different backing store, which means that all joins are made in memory, after the relevant related resources have been loaded from their individual data stores. Hopefully this answers your question.

Now, nothing prevents you from writing a [**custom** data handler](https://github.com/holidayextras/jsonapi-server/blob/master/documentation/handlers.md#creating-custom-handlers) for your existing database that you'll use for your resources. This would give you much freedom to implement the data retrieval as you see fit (although joins would still be done in memory by `jsonapi-server`, you could have the data already loaded from the database by a database side join and ready in memory).  That's the way I would approach your problem of exposing an existing data store to `jsonapi-server`.

What are your thoughts about writing a custom handler instead?

**Comment by oliversalzburg** [comment]
That is exactly the path we're on right now. 

Thanks for the background information. That has been extremely helpful. I'll also discard the partial work I've done on making the naming more customizable. I understand that it is not in line with the design of the module.
