### ISSUE TITLE
Upgrade to Sequelize 4

### ISSUE THREAD

**Issue by aledalgrande** [holidayextras/jsonapi-store-relationaldb#70]
Hi,

sequelize 4 has been out for a while, any reason why you are not updating? If I delete the sequelize version used by this library and force it to use v4, I get much better error messages.

**Comment by pmcnr-hx** [comment]
Are all the tests passing with Sequelize 4? If so, then there's no blocker for upgrading. Last time I tried Sequelize 4 tests were breaking. PRs are welcome!

**Comment by pmcnr-hx** [comment]
Closing. Implemented in #71.
