### ISSUE TITLE
You have an error in your SQL syntax near VIRTUAL

### ISSUE THREAD

**Issue by kriswill** [holidayextras/jsonapi-store-relationaldb#95]
For developer mode, I'm trying to populate a MySQL schema with a very simple resource.
* latest `jsonapi-store-relationaldb`and `jsonapi-server`
```
yarn versions v1.3.2
{ http_parser: '2.7.0',
  node: '8.9.1',
  v8: '6.1.534.47',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
✨  Done in 0.03s.
```

```js
// project.js
const { define, Joi } = require('jsonapi-server');

module.exports = handlers =>
    define({
        resource: 'projects',
        handlers,
        attributes: {
            name: Joi.string(),
            statusLabelGreen: Joi.string(),
            statusLabelYellow: Joi.string(),
            statusLabelRed: Joi.string(),
            images: Joi.many('images'),
            status: Joi.string()
        }
    });
```
The populate looks like this:
```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize(
    config.db.schema,
    config.db.username,
    config.db.password,
    config.db
);
const RelationalDbStore = require('jsonapi-store-relationaldb');
const relationalDbStore = new RelationalDbStore({sequelize});
require('./images')(relationalDbStore);
require('./projects')(relationalDbStore);

if (process.env.NODE_ENV === 'development') {
    relationalDbStore.populate({force: true}, function(error) {
        debug('store.populate: %O', error)
    });
}
```

The error message:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'VIRTUAL, `meta` VARCHAR(255), `name` TEXT, `statusLabelGreen` TEXT, `statusLabel\' at line 1'

the SQL:
```sql
CREATE TABLE IF NOT EXISTS `database-name.projects` (`id` CHAR(36) BINARY , `type` VIRTUAL, `meta` VARCHAR(255), `name` TEXT, `statusLabelGreen` TEXT, `statusLabelYellow` TEXT, `statusLabelRed` TEXT, `status` TEXT, PRIMARY KEY (`id`)) ENGINE=InnoDB;
```
The relevant call stack indicates this is happening in https://github.com/holidayextras/jsonapi-store-relationaldb/blob/master/lib/sqlHandler.js#L105

```js
self.baseModel.sync(options).asCallback(cb)
```
appears as if the Joi schema translation is picking up the `type VIRTUAL` facet, which it shouldn't be adding to the table.

Any help appreciated! 🍺

**Comment by paparomeo** [comment]
Interesting. I expected something like this to be caught by our automated tests. I'll try to reproduce it soon and come back to you with my findings.

**Comment by kriswill** [comment]
@paparomeo here's a similar report: https://github.com/sequelize/sequelize/issues/7599
seems like this issue has something to do with a random old version of sequelize.  It might not be related.

P.S., I we have standardized on yarn for our node projects.. Could this be causing this?

**Comment by kriswill** [comment]
Also, the tests didn't work for me right away, since I don't have a 'root' user on my local mysql, which is pretty common.  Instead I use the `mysql_config_editor` to generate a `~/.mylogin.cnf` file that is encrypted with credentials for the `[local]` path.  The `mysql` client will use the `local` path by default, instead of passing host/port/username/password information.  I had to remove the `-u root` from `setupDatabase.sh`

... anyways, maybe this belongs in another ticket.

**Comment by kriswill** [comment]
Here's an inspect of the `attributes` instance that is passed into `sequelize/lib/model.js` `static sync(options)` method, from `jsonapi-store-relationaldb/lib/sqlHandler.js` line 105.
```json
{ id: 
   { type: UUID {},
     defaultValue: 
      { [Function: UUIDV4]
        super_: [Object],
        warn: [Function: warn],
        key: 'UUIDV4',
        types: {} },
     primaryKey: true,
     Model: projects,
     fieldName: 'id',
     _modelAttribute: true,
     field: 'id' },
  type: 
   { type: VIRTUAL { returnType: undefined, fields: undefined },
     set: [Function: set],
     get: [Function: get],
     Model: projects,
     fieldName: 'type',
     _modelAttribute: true,
     field: 'type' },
  meta: 
   { type: STRING { options: [Object], _binary: undefined, _length: 255 },
     get: [Function: get],
     set: [Function: set],
     Model: projects,
     fieldName: 'meta',
     _modelAttribute: true,
     field: 'meta' },
  name: 
   { type: TEXT { options: [Object], _length: '' },
     allowNull: true,
     Model: projects,
     fieldName: 'name',
     _modelAttribute: true,
     field: 'name' },
  statusLabelGreen: 
   { type: TEXT { options: [Object], _length: '' },
     allowNull: true,
     Model: projects,
     fieldName: 'statusLabelGreen',
     _modelAttribute: true,
     field: 'statusLabelGreen' },
  statusLabelYellow: 
   { type: TEXT { options: [Object], _length: '' },
     allowNull: true,
     Model: projects,
     fieldName: 'statusLabelYellow',
     _modelAttribute: true,
     field: 'statusLabelYellow' },
  statusLabelRed: 
   { type: TEXT { options: [Object], _length: '' },
     allowNull: true,
     Model: projects,
     fieldName: 'statusLabelRed',
     _modelAttribute: true,
     field: 'statusLabelRed' },
  status: 
   { type: TEXT { options: [Object], _length: '' },
     allowNull: true,
     Model: projects,
     fieldName: 'status',
     _modelAttribute: true,
     field: 'status' } }
```

**Comment by kriswill** [comment]
@paparomeo after locking to sequelize `4.13.8` it does create the tables without the `type VIRTUAL`.  So, probably should check the version of sequelize before startup, to avoid breaking changes in sequelize `4.26.x`

**Comment by kriswill** [comment]
Also, discovered that each resource has to have it's own instance of the `jsonApiRelationalStore`.

```js
const RelationalDbStore = require('jsonapi-store-relationaldb');
const relationalDbStore = new RelationalDbStore({sequelize});
require('./images')(relationalDbStore);
require('./projects')(relationalDbStore);
```
it was only creating the `projects` and `projects-images` tables, but not the `images` table.

**Comment by pmcnr-hx** [comment]
Thank for the exhaustive diagnostic, @kriswill. You are correct that each resource needs its own store instance (which in the case of the relationaldb store is then shared between resources behind the scenes). The design decision was made so you could mix and match resources backed by multiple stores.

I have meanwhile released a new version of the project which depends on Sequelize 4.28 and shouldn't have the problem you reported with the VIRTUAL columsn anymore (unfortunately Sequelize doesn't do semantic versioning for their projects and breaking changes sneak in too easily).

If you can give the latest version a try and are happy with it we can then close this issue. If you have other separate queries please feel free to open a new issue for those. Thanks again for your interest in the project.

**Comment by kriswill** [comment]
Thanks for getting back @pmcnr-hx!  I will re-test with the latest version, and close the issue if the problem no longer occurs.

**Comment by kriswill** [comment]
Works perfectly:

```diff
→ g patch
diff --git a/package.json b/package.json
index a55e081..b457c3e 100644
--- a/package.json
+++ b/package.json
@@ -22,8 +22,8 @@
     "express": "^4.16.2",
     "express-domain-middleware": "^0.1.0",
     "express-tracking": "^1.0.1",
-    "jsonapi-server": "^4.1.1",
-    "jsonapi-store-relationaldb": "^4.0.0",
+    "jsonapi-server": "^4.1.2",
+    "jsonapi-store-relationaldb": "^5.0.0",
     "lodash": "^4.17.4",
     "multer": "^1.3.0",
     "mysql2": "^1.5.1",
@@ -32,7 +32,7 @@
     "query-parse": "^2.0.0",
     "request": "^2.83.0",
     "request-promise": "^4.2.2",
-    "sequelize": "4.13.8",
+    "sequelize": "4.28.0",
     "signalfx": "^5.0.0",
     "uuid": "^3.1.0"
   },
```
